// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiBase.Db;

#nullable disable

namespace WebApiBase.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20220811021641_UpdateDIDProp")]
    partial class UpdateDIDProp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApiBase.Models.RelationalDataBase.DataView", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<string>("Creator")
                        .HasColumnType("varchar(30)")
                        .HasComment("创建人");

                    b.Property<int?>("DBID")
                        .HasColumnType("int");

                    b.Property<string>("SqlText")
                        .HasColumnType("longtext")
                        .HasComment("sql语句");

                    b.Property<string>("VNName")
                        .HasColumnType("varchar(255)")
                        .HasComment("视图名称");

                    b.HasKey("ID");

                    b.HasIndex("DBID");

                    b.ToTable("data_view");
                });

            modelBuilder.Entity("WebApiBase.Models.RelationalDataBase.DBConnection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<string>("Creator")
                        .HasColumnType("varchar(30)")
                        .HasComment("创建人");

                    b.Property<string>("DBIP")
                        .HasColumnType("varchar(20)")
                        .HasComment("数据库IP");

                    b.Property<string>("DBName")
                        .HasColumnType("varchar(50)")
                        .HasComment("数据库名");

                    b.Property<string>("DBPassword")
                        .HasColumnType("varchar(255)")
                        .HasComment("数据库密码");

                    b.Property<string>("DBPort")
                        .HasColumnType("varchar(5)")
                        .HasComment("数据库端口");

                    b.Property<int>("DBType")
                        .HasColumnType("int")
                        .HasComment("0 Mysql;1 SqlServer;2 Oracle");

                    b.Property<string>("DBUser")
                        .HasColumnType("varchar(20)")
                        .HasComment("数据库用户");

                    b.HasKey("ID");

                    b.ToTable("db_connection");
                });

            modelBuilder.Entity("WebApiBase.Models.Test", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("pwd")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("test");
                });

            modelBuilder.Entity("WebApiBase.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID");

                    b.Property<string>("Pwd")
                        .HasColumnType("longtext")
                        .HasComment("密码");

                    b.Property<string>("Role")
                        .HasColumnType("longtext")
                        .HasComment("角色");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext")
                        .HasComment("用户名");

                    b.HasKey("ID");

                    b.ToTable("user");
                });

            modelBuilder.Entity("WebApiBase.Models.RelationalDataBase.DataView", b =>
                {
                    b.HasOne("WebApiBase.Models.RelationalDataBase.DBConnection", "DB")
                        .WithMany()
                        .HasForeignKey("DBID");

                    b.Navigation("DB");
                });
#pragma warning restore 612, 618
        }
    }
}
